export {
  ASSISTANT_SYSTEM_PROMPT,
  MODULE_TRANSITION_PROMPTS,
  REFRESH_HIGHLIGHTING_PROMPT,
  TEXT_FORMAT_CONTRACT,
  TRANSLATE_SYSTEM_PROMPT,
  getTransitionPrompt
} from "@/lib/modulePromptRegistry";
